spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123123
    username: root
    url: jdbc:mysql://localhost:3306/shiro
    type: com.alibaba.druid.pool.DruidDataSource
mapper:
  mappers: com.webws.xpf.utils.MyMapper
  not-empty: false
  identity: MYSQL

# redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-wait: -1ms
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 20000